controller_manager:
  ros__parameters:
    use_sim_time: True
    update_rate: 1000  # Hz

    joint_states_controller:
      type: joint_state_broadcaster/JointStateBroadcaster

    effort_controller:
      type: effort_controllers/JointGroupEffortController

effort_controller:
  ros__parameters:
    use_sim_time: True
    joints:
      - rear_left_joint
      - rear_right_joint
      - mid_left_joint
      - mid_right_joint
      - front_left_joint
      - front_right_joint 
    command_interfaces:
      - effort
    state_interfaces:
      - effort
      - position
      - velocity
    
    # gains:
    #   rear_left_joint   : {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
    #   rear_right_joint  : {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
    #   mid_left_joint    : {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
    #   mid_right_joint   : {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
    #   front_left_joint  : {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
    #   front_right_joint : {p: 100.0, i: 0.2, d: 1.0, i_clamp: 2.5}
      